-- features/chapter04-*.feature, translated one scenario at a time.
local T = require("helpers")
local tuple_mod = require("tuple")
local matrix_mod = require("matrix")
local shapes_mod = require("shapes")
local coverage_mod = require("coverage")
local canvas_mod = require("canvas")
local ppm_mod = require("ppm")
local lines_mod = require("lines")
local renders = require("renders")

local point, vector = tuple_mod.point, tuple_mod.vector
local magnitude, normalize, dot, cross = tuple_mod.magnitude, tuple_mod.normalize, tuple_mod.dot, tuple_mod.cross

local matrix3, mat_get, identity, transpose, determinant, is_invertible, inverse =
    matrix_mod.matrix3, matrix_mod.mat_get, matrix_mod.identity, matrix_mod.transpose,
    matrix_mod.determinant, matrix_mod.is_invertible, matrix_mod.inverse
local translation, scaling, rotation, shearing, approx_scale, transform_points =
    matrix_mod.translation, matrix_mod.scaling, matrix_mod.rotation, matrix_mod.shearing,
    matrix_mod.approx_scale, matrix_mod.transform_points

local segment, shape_union, transformed, thick_line, outline, inside, rasterize =
    shapes_mod.segment, shapes_mod.union, shapes_mod.transformed, shapes_mod.thick_line,
    shapes_mod.outline, shapes_mod.inside, shapes_mod.rasterize
local ink = coverage_mod.ink
local canvas, pixel_at, write_pixel, fill = canvas_mod.canvas, canvas_mod.pixel_at, canvas_mod.write_pixel, canvas_mod.fill
local canvas_to_p6, ppm_pixel, max_channel_difference, read_file =
    ppm_mod.canvas_to_p6, ppm_mod.ppm_pixel, ppm_mod.max_channel_difference, ppm_mod.read_file
local color_mod = require("color")
local color = color_mod.color

local PI = math.pi

-- helper: build a matrix from a Gherkin data table given row by row
local function table_matrix(rows)
  local vals = {}
  for _, row in ipairs(rows) do
    for _, v in ipairs(row) do vals[#vals + 1] = v end
  end
  return matrix3(table.unpack(vals))
end

-- ---- chapter04-tuples.feature -----------------------------------------------

T.test("A point has w = 1", function()
  local p = point(4, -4)
  T.assert_eq(p.x, 4); T.assert_eq(p.y, -4); T.assert_eq(p.w, 1)
end)

T.test("A vector has w = 0", function()
  local v = vector(4, -4)
  T.assert_eq(v.x, 4); T.assert_eq(v.y, -4); T.assert_eq(v.w, 0)
end)

T.test("The difference of two points is the vector between them", function()
  local a, b = point(3, 2), point(5, 6)
  T.assert_tuple_eq(b - a, vector(2, 4))
  T.assert_tuple_eq(a - b, vector(-2, -4))
end)

T.test("A point plus a vector is a point", function()
  local p, v = point(3, -2), vector(-2, 3)
  T.assert_tuple_eq(p + v, point(1, 1))
  T.assert_tuple_eq(p - v, point(5, -5))
end)

T.test("A vector plus a vector is a vector", function()
  local a, b = vector(3, -2), vector(-2, 3)
  T.assert_tuple_eq(a + b, vector(1, 1))
  T.assert_tuple_eq(a - b, vector(5, -5))
end)

T.test("Negating, scaling and dividing a vector", function()
  local v = vector(1, -2)
  T.assert_tuple_eq(-v, vector(-1, 2))
  T.assert_tuple_eq(v * 3.5, vector(3.5, -7))
  T.assert_tuple_eq(v * 0.5, vector(0.5, -1))
  T.assert_tuple_eq(v / 2, vector(0.5, -1))
end)

T.test("The magnitude of a vector", function()
  T.assert_eq(magnitude(vector(1, 0)), 1)
  T.assert_eq(magnitude(vector(0, 1)), 1)
  T.assert_eq(magnitude(vector(3, 4)), 5)
  T.assert_eq(magnitude(vector(-3, -4)), 5)
  T.assert_eq(magnitude(vector(-1, -2)), 2.2361)
end)

T.test("Normalizing a vector", function()
  T.assert_tuple_eq(normalize(vector(4, 0)), vector(1, 0))
  T.assert_tuple_eq(normalize(vector(1, 2)), vector(0.4472, 0.8944))
  T.assert_eq(magnitude(normalize(vector(1, 2))), 1)
end)

T.test("The dot product of two vectors", function()
  local a, b = vector(1, 2), vector(2, 3)
  T.assert_eq(dot(a, b), 8)
  T.assert_eq(dot(a, vector(-2, 1)), 0)
end)

T.test("magnitude and dot look at x and y only", function()
  T.assert_eq(magnitude(point(3, 4)), 5)
  T.assert_eq(dot(point(1, 2), point(2, 3)), 8)
end)

T.test("The cross product of two vectors is a number", function()
  local a, b = vector(1, 0), vector(0, 1)
  T.assert_eq(cross(a, b), 1)
  T.assert_eq(cross(b, a), -1)
  T.assert_eq(cross(a, a), 0)
  T.assert_eq(cross(vector(2, 3), vector(4, 5)), -2)
end)

T.test("The sign of the cross product says which side of a line a point is on", function()
  local a, b = point(0, 0), point(10, 0)
  T.assert_eq(cross(b - a, point(5, 3) - a), 30)
  T.assert_eq(cross(b - a, point(5, -3) - a), -30)
  T.assert_eq(cross(b - a, point(20, 0) - a), 0)
end)

-- ---- chapter04-matrices.feature -----------------------------------------------

T.test("Constructing and inspecting a matrix", function()
  local M = table_matrix({ { 1, 2, 3 }, { 4, 5, 6 }, { 7, 8, 9 } })
  T.assert_eq(mat_get(M, 0, 0), 1)
  T.assert_eq(mat_get(M, 0, 2), 3)
  T.assert_eq(mat_get(M, 1, 0), 4)
  T.assert_eq(mat_get(M, 1, 1), 5)
  T.assert_eq(mat_get(M, 2, 0), 7)
  T.assert_eq(mat_get(M, 2, 2), 9)
  T.assert_mat_eq(M, matrix3(1, 2, 3, 4, 5, 6, 7, 8, 9))
end)

T.test("Matrix equality with identical matrices", function()
  local A = matrix3(1, 2, 3, 4, 5, 6, 7, 8, 9)
  local B = matrix3(1, 2, 3, 4, 5, 6, 7, 8, 9)
  T.assert_mat_eq(A, B)
end)

T.test("Matrix equality with different matrices", function()
  local A = matrix3(1, 2, 3, 4, 5, 6, 7, 8, 9)
  local B = matrix3(1, 2, 3, 4, 5, 6, 7, 8, 8)
  T.assert_false(T.mat_eq(A, B))
end)

T.test("Multiplying two matrices", function()
  local A = table_matrix({ { 1, 2, 3 }, { 4, 5, 6 }, { 7, 8, 9 } })
  local B = table_matrix({ { 2, -1, 0 }, { 1, 3, 1 }, { 0, 1, 2 } })
  local expected = table_matrix({ { 4, 8, 8 }, { 13, 17, 17 }, { 22, 26, 26 } })
  T.assert_mat_eq(A * B, expected)
end)

T.test("Matrix multiplication is not commutative", function()
  local A = matrix3(1, 2, 3, 4, 5, 6, 7, 8, 9)
  local B = matrix3(2, -1, 0, 1, 3, 1, 0, 1, 2)
  T.assert_false(T.mat_eq(A * B, B * A))
end)

T.test("A matrix multiplied by a point", function()
  local A = table_matrix({ { 1, 2, 3 }, { 4, 5, 6 }, { 0, 0, 1 } })
  local p = point(1, 2)
  T.assert_tuple_eq(A * p, point(8, 20))
end)

T.test("A matrix multiplied by a vector ignores the last column", function()
  local A = table_matrix({ { 1, 2, 3 }, { 4, 5, 6 }, { 0, 0, 1 } })
  local v = vector(1, 2)
  T.assert_tuple_eq(A * v, vector(5, 14))
end)

T.test("Multiplying by the identity matrix changes nothing", function()
  local A = matrix3(0, 1, 2, 1, 2, 4, 2, 4, 8)
  local p = point(1, 2)
  T.assert_mat_eq(A * identity(), A)
  T.assert_mat_eq(identity() * A, A)
  T.assert_tuple_eq(identity() * p, p)
end)

T.test("Transposing a matrix", function()
  local A = table_matrix({ { 0, 9, 3 }, { 9, 8, 0 }, { 1, 8, 5 } })
  local expected = table_matrix({ { 0, 9, 1 }, { 9, 8, 8 }, { 3, 0, 5 } })
  T.assert_mat_eq(transpose(A), expected)
end)

T.test("Transposing the identity matrix", function()
  T.assert_mat_eq(transpose(identity()), identity())
end)

T.test("The determinant of a 3 by 3 matrix", function()
  local A = table_matrix({ { 1, 2, 6 }, { -5, 8, -4 }, { 2, 6, 4 } })
  T.assert_eq(determinant(A), -196)
end)

T.test("The determinant of a transform is the area factor", function()
  T.assert_eq(determinant(identity()), 1)
  T.assert_eq(determinant(scaling(2, 3)), 6)
  T.assert_eq(determinant(rotation(0.7)), 1)
  T.assert_eq(determinant(translation(4, 9)), 1)
  T.assert_eq(determinant(scaling(-1, 1)), -1)
end)

T.test("Testing an invertible matrix for invertibility", function()
  local A = table_matrix({ { 3, 0, 2 }, { 2, 0, -2 }, { 0, 1, 1 } })
  T.assert_eq(determinant(A), 10)
  T.assert_true(is_invertible(A))
end)

T.test("Testing a non-invertible matrix for invertibility", function()
  local A = table_matrix({ { 1, 2, 3 }, { 2, 4, 6 }, { 0, 0, 1 } })
  T.assert_eq(determinant(A), 0)
  T.assert_false(is_invertible(A))
end)

T.test("Invertibility is an exact test against zero", function()
  T.assert_true(is_invertible(scaling(0.0001, 1)))
  T.assert_exact(determinant(scaling(0.0001, 1)), 0.0001)
  T.assert_tuple_eq(inverse(scaling(0.0001, 1)) * point(0.0001, 3), point(1, 3))
end)

T.test("Calculating the inverse of a matrix", function()
  local A = table_matrix({ { 3, 0, 2 }, { 2, 0, -2 }, { 0, 1, 1 } })
  local B = inverse(A)
  T.assert_eq(mat_get(B, 0, 0), 0.2)
  T.assert_eq(mat_get(B, 1, 2), 1)
  T.assert_eq(mat_get(B, 2, 1), -0.3)
  local expected = table_matrix({ { 0.2, 0.2, 0 }, { -0.2, 0.3, 1 }, { 0.2, -0.3, 0 } })
  T.assert_mat_eq(B, expected)
  T.assert_mat_eq(A * B, identity())
end)

T.test("Multiplying a product by its inverse", function()
  local A = matrix3(1, 2, 3, 4, 5, 6, 7, 8, 9)
  local B = matrix3(2, -1, 0, 1, 3, 1, 0, 1, 2)
  local C = A * B
  T.assert_mat_eq(C * inverse(B), A)
end)

T.test("The inverse of a transform is a transform", function()
  local A = translation(5, -3) * rotation(PI / 6) * scaling(2, 3)
  local B = inverse(A)
  T.assert_eq(mat_get(B, 2, 0), 0)
  T.assert_eq(mat_get(B, 2, 1), 0)
  T.assert_eq(mat_get(B, 2, 2), 1)
  T.assert_eq(mat_get(B, 0, 0), 0.4330)
  T.assert_eq(mat_get(B, 0, 2), -1.4151)
  T.assert_eq(mat_get(B, 1, 2), 1.6994)
  T.assert_mat_eq(B * A, identity())
end)

-- ---- chapter04-transforms.feature -----------------------------------------------

T.test("Multiplying by a translation matrix", function()
  local t, p = translation(5, -3), point(-3, 4)
  T.assert_tuple_eq(t * p, point(2, 1))
end)

T.test("The inverse of a translation moves the other way", function()
  local t, p = translation(5, -3), point(-3, 4)
  T.assert_tuple_eq(inverse(t) * p, point(-8, 7))
end)

T.test("Translation does not affect vectors", function()
  local t, v = translation(5, -3), vector(-3, 4)
  T.assert_tuple_eq(t * v, v)
end)

T.test("A scaling matrix applied to a point", function()
  local s, p = scaling(2, 3), point(-4, 6)
  T.assert_tuple_eq(s * p, point(-8, 18))
end)

T.test("A scaling matrix applied to a vector", function()
  local s, v = scaling(2, 3), vector(-4, 6)
  T.assert_tuple_eq(s * v, vector(-8, 18))
end)

T.test("The inverse of a scaling shrinks", function()
  local s, v = scaling(2, 3), vector(-4, 6)
  T.assert_tuple_eq(inverse(s) * v, vector(-2, 2))
end)

T.test("Reflection is scaling by a negative value", function()
  local s, p = scaling(-1, 1), point(2, 3)
  T.assert_tuple_eq(s * p, point(-2, 3))
end)

T.test("A positive rotation turns x toward y", function()
  local p = point(1, 0)
  T.assert_tuple_eq(rotation(PI / 4) * p, point(0.7071, 0.7071))
  T.assert_tuple_eq(rotation(PI / 2) * p, point(0, 1))
  T.assert_tuple_eq(rotation(PI) * p, point(-1, 0))
end)

T.test("The inverse of a rotation turns the other way", function()
  local p = point(1, 0)
  T.assert_tuple_eq(inverse(rotation(PI / 4)) * p, point(0.7071, -0.7071))
  T.assert_tuple_eq(rotation(-PI / 4) * p, point(0.7071, -0.7071))
end)

T.test("A rotation preserves length", function()
  local v = vector(3, 4)
  T.assert_eq(magnitude(rotation(1.2) * v), 5)
  T.assert_eq(magnitude(rotation(-2.8) * v), 5)
end)

T.test("Shearing moves x in proportion to y", function()
  local s, p = shearing(1, 0), point(2, 3)
  T.assert_tuple_eq(s * p, point(5, 3))
end)

T.test("Shearing moves y in proportion to x", function()
  local s, p = shearing(0, 1), point(2, 3)
  T.assert_tuple_eq(s * p, point(2, 5))
end)

T.test("Individual transformations are applied in sequence", function()
  local p = point(1, 0)
  local A, B, C = rotation(PI / 2), scaling(5, 5), translation(10, 5)
  local p2 = A * p
  local p3 = B * p2
  local p4 = C * p3
  T.assert_tuple_eq(p2, point(0, 1))
  T.assert_tuple_eq(p3, point(0, 5))
  T.assert_tuple_eq(p4, point(10, 10))
end)

T.test("Chained transformations must be applied in reverse order", function()
  local p = point(1, 0)
  local A, B, C = rotation(PI / 2), scaling(5, 5), translation(10, 5)
  local Tm = C * B * A
  T.assert_tuple_eq(Tm * p, point(10, 10))
end)

T.test("The other order is a different transform", function()
  local p = point(1, 0)
  local A, B, C = rotation(PI / 2), scaling(5, 5), translation(10, 5)
  local Tm = A * B * C
  T.assert_tuple_eq(Tm * p, point(-25, 55))
end)

T.test("Rotating about a point that isn't the origin", function()
  local Tm = translation(4, 4) * rotation(PI / 2) * translation(-4, -4)
  T.assert_tuple_eq(Tm * point(6, 4), point(4, 6))
  T.assert_tuple_eq(Tm * point(4, 4), point(4, 4))
end)

-- ---- chapter04-scale.feature -----------------------------------------------

T.test("The identity, a translation and a rotation don't stretch", function()
  T.assert_eq(approx_scale(identity()), 1)
  T.assert_eq(approx_scale(translation(7, 9)), 1)
  T.assert_eq(approx_scale(rotation(1.1)), 1)
end)

T.test("A uniform scale is reported exactly", function()
  T.assert_eq(approx_scale(scaling(2, 2)), 2)
  T.assert_eq(approx_scale(scaling(0.5, 0.5)), 0.5)
  T.assert_eq(approx_scale(scaling(3, 3) * rotation(0.7)), 3)
  T.assert_eq(approx_scale(translation(5, 5) * scaling(3, 3)), 3)
end)

T.test("A reflection is not a negative scale", function()
  T.assert_eq(approx_scale(scaling(-2, 2)), 2)
end)

T.test("A non-uniform scale is reported as the geometric mean", function()
  T.assert_eq(approx_scale(scaling(4, 1)), 2)
  T.assert_eq(approx_scale(scaling(4, 1) * rotation(0.4)), 2)
  T.assert_eq(approx_scale(scaling(9, 1)), 3)
end)

T.test("A shear that preserves area reports 1", function()
  T.assert_eq(approx_scale(shearing(1, 0)), 1)
  T.assert_eq(approx_scale(shearing(0.5, 0.5)), 0.8660)
end)

T.test("A collapsed transform reports 0", function()
  T.assert_eq(approx_scale(scaling(0, 1)), 0)
  T.assert_eq(approx_scale(matrix3(1, 2, 0, 2, 4, 0, 0, 0, 1)), 0)
end)

-- ---- chapter04-drawing.feature -----------------------------------------------

T.test("A segment between pixel centers is a thick line", function()
  local s = segment(point(2.5, 2.5), point(11.5, 5.5), 1)
  local cov = rasterize(s, 16, 10)
  T.assert_eq(coverage_mod.coverage_at(cov, 2, 2), 0.484375)
  T.assert_eq(coverage_mod.coverage_at(cov, 11, 5), 0.484375)
  T.assert_eq(coverage_mod.coverage_at(cov, 6, 3), 0.6875)
  T.assert_eq(coverage_mod.coverage_at(cov, 7, 3), 0.359375)
  T.assert_eq(coverage_mod.coverage_at(cov, 2, 1), 0)
  T.assert_eq(ink(cov), 9.4063)
end)

T.test("A segment need not start on a pixel center", function()
  local s = segment(point(1, 3.5), point(7, 3.5), 1)
  local cov = rasterize(s, 10, 10)
  T.assert_eq(coverage_mod.coverage_at(cov, 0, 3), 0)
  T.assert_eq(coverage_mod.coverage_at(cov, 1, 3), 1)
  T.assert_eq(coverage_mod.coverage_at(cov, 6, 3), 1)
  T.assert_eq(coverage_mod.coverage_at(cov, 7, 3), 0)
  T.assert_eq(coverage_mod.coverage_at(cov, 3, 2), 0)
  T.assert_eq(ink(cov), 6)
end)

T.test("A segment of no length is a square", function()
  local s = segment(point(3.5, 3.5), point(3.5, 3.5), 1)
  local cov = rasterize(s, 8, 8)
  T.assert_eq(coverage_mod.coverage_at(cov, 3, 3), 1)
  T.assert_eq(ink(cov), 1)
end)

T.test("A union of nothing is inside nowhere", function()
  local s = shape_union({})
  T.assert_false(inside(s, 0, 0))
  T.assert_eq(ink(rasterize(s, 4, 4)), 0)
end)

T.test("A union is inside when any of its parts is", function()
  local s = shape_union({ shapes_mod.circle(2, 2, 1), shapes_mod.rectangle(5, 0, 7, 4) })
  T.assert_true(inside(s, 2, 2))
  T.assert_true(inside(s, 6, 1))
  T.assert_false(inside(s, 4, 2))
  T.assert_eq(ink(rasterize(s, 8, 8)), 11.25)
end)

T.test("A circle seen through a scale is an ellipse", function()
  local s = transformed(shapes_mod.circle(0, 0, 4), scaling(2, 1))
  T.assert_true(inside(s, 7.9, 0))
  T.assert_false(inside(s, 8.1, 0))
  T.assert_true(inside(s, 0, 3.9))
  T.assert_false(inside(s, 0, 4.1))
  T.assert_true(inside(s, 5.6, 1.4))
  T.assert_false(inside(s, 5.6, 2.9))
end)

T.test("The transform is applied in the order the matrix says", function()
  local s = transformed(shapes_mod.circle(0, 0, 4), translation(10, 10) * scaling(2, 1))
  T.assert_true(inside(s, 10, 10))
  T.assert_true(inside(s, 17.9, 10))
  T.assert_false(inside(s, 18.1, 10))
  T.assert_true(inside(s, 10, 13.9))
  T.assert_false(inside(s, 10, 14.1))
end)

T.test("A shape seen through a collapsed transform is empty", function()
  local s = transformed(shapes_mod.circle(0, 0, 4), scaling(0, 1))
  T.assert_false(inside(s, 0, 0))
  T.assert_eq(ink(rasterize(s, 10, 10)), 0)
end)

T.test("A pen in shape space scales with the shape", function()
  local s = transformed(thick_line(5, 0, 5, 9, 1), scaling(3, 1))
  local cov = rasterize(s, 24, 10)
  T.assert_eq(coverage_mod.coverage_at(cov, 14, 4), 0)
  T.assert_eq(coverage_mod.coverage_at(cov, 15, 4), 1)
  T.assert_eq(coverage_mod.coverage_at(cov, 16, 4), 1)
  T.assert_eq(coverage_mod.coverage_at(cov, 17, 4), 1)
  T.assert_eq(coverage_mod.coverage_at(cov, 18, 4), 0)
  T.assert_eq(ink(cov), 27)
end)

T.test("A pen in device space does not", function()
  local m = scaling(3, 1)
  local s = segment(m * point(5.5, 0.5), m * point(5.5, 9.5), 1)
  local cov = rasterize(s, 24, 10)
  T.assert_eq(coverage_mod.coverage_at(cov, 15, 4), 0)
  T.assert_eq(coverage_mod.coverage_at(cov, 16, 4), 1)
  T.assert_eq(coverage_mod.coverage_at(cov, 17, 4), 0)
  T.assert_eq(ink(cov), 9)
end)

T.test("Dividing the width by approx_scale makes the two pens agree", function()
  local m = scaling(2, 2)
  local s = transformed(segment(point(5.5, 0.5), point(5.5, 9.5), 1 / approx_scale(m)), m)
  local cov = rasterize(s, 24, 20)
  T.assert_eq(coverage_mod.coverage_at(cov, 9, 5), 0)
  T.assert_eq(coverage_mod.coverage_at(cov, 10, 5), 0.5)
  T.assert_eq(coverage_mod.coverage_at(cov, 11, 5), 0.5)
  T.assert_eq(coverage_mod.coverage_at(cov, 12, 5), 0)
  T.assert_eq(ink(cov), 18)
end)

T.test("Under a non-uniform scale the compromise shows", function()
  local m = scaling(4, 1)
  local w = 1 / approx_scale(m)
  local v = transformed(segment(point(2.5, 0.5), point(2.5, 9.5), w), m)
  local h = transformed(segment(point(0.5, 5.5), point(4.5, 5.5), w), m)
  local cv = rasterize(v, 24, 12)
  local ch = rasterize(h, 24, 12)
  T.assert_eq(coverage_mod.coverage_at(cv, 8, 5), 0)
  T.assert_eq(coverage_mod.coverage_at(cv, 9, 5), 1)
  T.assert_eq(coverage_mod.coverage_at(cv, 10, 5), 1)
  T.assert_eq(coverage_mod.coverage_at(cv, 11, 5), 0)
  T.assert_eq(ink(cv), 18)
  T.assert_eq(coverage_mod.coverage_at(ch, 10, 4), 0)
  T.assert_eq(coverage_mod.coverage_at(ch, 10, 5), 0.5)
  T.assert_eq(coverage_mod.coverage_at(ch, 10, 6), 0)
  T.assert_eq(ink(ch), 8)
end)

T.test("An outline is one shape, so its corners are painted once", function()
  local pts = { point(1.5, 1.5), point(6.5, 1.5), point(6.5, 6.5), point(1.5, 6.5) }
  local c = canvas(8, 8)
  coverage_mod.paint_through(c, rasterize(outline(pts, identity(), 1), 8, 8), color(1, 1, 1))
  T.assert_exact(#T.lit_pixels(c), 20)
  T.assert_color_eq(pixel_at(c, 3, 1), color(1, 1, 1))
  T.assert_color_eq(pixel_at(c, 1, 3), color(1, 1, 1))
  T.assert_color_eq(pixel_at(c, 1, 1), color(0.75, 0.75, 0.75))
  T.assert_color_eq(pixel_at(c, 3, 3), color(0, 0, 0))
  T.assert_color_eq(pixel_at(c, 0, 1), color(0, 0, 0))
  T.assert_eq(lines_mod.total_ink(c), 19)
end)

T.test("An outline takes its points through the matrix first", function()
  local pts = { point(1.5, 1.5), point(6.5, 1.5), point(6.5, 6.5), point(1.5, 6.5) }
  local c = canvas(16, 16)
  coverage_mod.paint_through(c, rasterize(outline(pts, scaling(2, 2), 1), 16, 16), color(1, 1, 1))
  T.assert_exact(#T.lit_pixels(c), 76)
  T.assert_color_eq(pixel_at(c, 3, 3), color(0.75, 0.75, 0.75))
  T.assert_color_eq(pixel_at(c, 8, 2), color(0.5, 0.5, 0.5))
  T.assert_color_eq(pixel_at(c, 8, 3), color(0.5, 0.5, 0.5))
  T.assert_color_eq(pixel_at(c, 8, 4), color(0, 0, 0))
end)

-- ---- chapter04-plate.feature -----------------------------------------------

T.test("The fan as points", function()
  local pts = renders.fan_points()
  T.assert_exact(#pts, 13)
  T.assert_tuple_eq(pts[1], point(0, 0))
  T.assert_tuple_eq(pts[2], point(36, 0))
  T.assert_tuple_eq(pts[5], point(0, 36))
  T.assert_tuple_eq(pts[8], point(-36, 0))
  T.assert_tuple_eq(pts[3], point(31.1769, 18))
end)

T.test("Rotate, then translate: the fan turns about its own center", function()
  local m = translation(104.5, 76.5) * rotation(PI / 6)
  local pts = transform_points(renders.fan_points(), m)
  T.assert_tuple_eq(pts[1], point(104.5, 76.5))
  T.assert_tuple_eq(pts[2], point(135.6769, 94.5))
  T.assert_tuple_eq(pts[5], point(86.5, 107.6769))
end)

T.test("Translate, then rotate: the fan swings about the canvas corner", function()
  local m = rotation(PI / 6) * translation(104.5, 76.5)
  local pts = transform_points(renders.fan_points(), m)
  T.assert_tuple_eq(pts[1], point(52.2497, 118.5009))
  T.assert_tuple_eq(pts[2], point(83.4266, 136.5009))
end)

T.test("The letter F", function()
  local f = renders.letter_f()
  T.assert_exact(#f, 10)
  T.assert_tuple_eq(f[1], point(-20, -30))
  T.assert_tuple_eq(f[2], point(20, -30))
  T.assert_tuple_eq(f[6], point(12, -5))
  T.assert_tuple_eq(f[10], point(-20, 30))
end)

T.test("The F at home", function()
  local f = transform_points(renders.letter_f(), translation(44.5, 44.5))
  T.assert_tuple_eq(f[1], point(24.5, 14.5))
  T.assert_tuple_eq(f[2], point(64.5, 14.5))
  T.assert_tuple_eq(f[10], point(24.5, 74.5))
end)

T.test("The F, rotated then translated", function()
  local m = translation(104.5, 76.5) * rotation(PI / 6)
  local f = transform_points(renders.letter_f(), m)
  T.assert_tuple_eq(f[1], point(102.1795, 40.5192))
  T.assert_tuple_eq(f[2], point(136.8205, 60.5192))
  T.assert_tuple_eq(f[6], point(117.3923, 78.1699))
  T.assert_tuple_eq(f[10], point(72.1795, 92.4808))
end)

T.test("The F, translated then rotated", function()
  local m = rotation(PI / 6) * translation(104.5, 76.5)
  local f = transform_points(renders.letter_f(), m)
  T.assert_tuple_eq(f[1], point(49.9291, 82.5202))
  T.assert_tuple_eq(f[2], point(84.5702, 102.5202))
  T.assert_tuple_eq(f[6], point(65.142, 120.1708))
  T.assert_tuple_eq(f[10], point(19.9291, 134.4817))
end)

T.test("side_by_side puts the first canvas on the left", function()
  local a, b = canvas(2, 3), canvas(4, 3)
  fill(a, color(1, 0, 0))
  fill(b, color(0, 0, 1))
  local c = renders.side_by_side(a, b)
  T.assert_exact(c.width, 6)
  T.assert_exact(c.height, 3)
  T.assert_color_eq(pixel_at(c, 0, 0), color(1, 0, 0))
  T.assert_color_eq(pixel_at(c, 1, 2), color(1, 0, 0))
  T.assert_color_eq(pixel_at(c, 2, 0), color(0, 0, 1))
  T.assert_color_eq(pixel_at(c, 5, 2), color(0, 0, 1))
end)

T.test("The fan, both orders", function()
  local c = renders.fan_both_orders()
  local ref = read_file("reference/chapter-04/fan-both-orders.ppm")
  local p6 = canvas_to_p6(c)
  T.assert_exact(c.width, 320)
  T.assert_exact(c.height, 160)
  local function check(x, y, rr, gg, bb)
    local r, g, b = ppm_pixel(p6, x, y)
    T.assert_eq(r, rr, 1); T.assert_eq(g, gg, 1); T.assert_eq(b, bb, 1)
  end
  check(104, 76, 246, 246, 241)
  check(124, 76, 246, 246, 241)
  check(104, 56, 246, 246, 241)
  check(125, 88, 236, 236, 231)
  check(116, 97, 236, 236, 231)
  check(141, 76, 39, 39, 44)
  check(10, 10, 39, 39, 44)
  check(212, 118, 246, 246, 241)
  check(232, 118, 246, 246, 241)
  check(233, 130, 223, 223, 219)
  check(224, 139, 236, 236, 231)
  check(200, 139, 211, 211, 207)
  check(310, 10, 39, 39, 44)
  T.assert_true(max_channel_difference(p6, ref) <= 1)
end)

T.test("Plate 4", function()
  local c = renders.plate_04()
  local ref = read_file("reference/chapter-04/plate-04.ppm")
  local p6 = canvas_to_p6(c)
  T.assert_exact(c.width, 640)
  T.assert_exact(c.height, 320)
  local function check(x, y, rr, gg, bb)
    local r, g, b = ppm_pixel(p6, x, y)
    T.assert_eq(r, rr, 1); T.assert_eq(g, gg, 1); T.assert_eq(b, bb, 1)
  end
  check(48, 28, 99, 99, 102)
  check(80, 28, 111, 111, 115)
  check(48, 100, 111, 111, 115)
  check(10, 10, 39, 39, 44)
  check(200, 150, 39, 39, 44)
  check(268, 129, 237, 237, 233)
  check(215, 145, 237, 237, 233)
  check(239, 101, 237, 237, 233)
  check(174, 173, 217, 217, 213)
  check(368, 28, 99, 99, 102)
  check(500, 60, 39, 39, 44)
  check(453, 207, 236, 236, 231)
  check(431, 229, 234, 234, 229)
  check(445, 249, 234, 234, 229)
  check(368, 273, 177, 177, 174)
  T.assert_true(max_channel_difference(p6, ref) <= 1)
end)
