-- features/chapter06-*.feature, translated one scenario at a time.
local T = require("helpers")
local tuple_mod = require("tuple")
local path_mod = require("path")
local sweep_mod = require("sweep")
local coverage_mod = require("coverage")
local shapes_mod = require("shapes")
local winding_mod = require("winding")
local matrix_mod = require("matrix")
local ppm_mod = require("ppm")
local renders = require("renders")

local point = tuple_mod.point
local path, move_to, line_to, close, subpaths, edges, bounds, polygon =
    path_mod.path, path_mod.move_to, path_mod.line_to, path_mod.close, path_mod.subpaths,
    path_mod.edges, path_mod.bounds, path_mod.polygon
local circle_path = path_mod.circle_path

local edge_table, x_at, crossings_on_row, spans_from_crossings, spans, fill_span, fill_path_aliased, transform_path =
    sweep_mod.edge_table, sweep_mod.x_at, sweep_mod.crossings_on_row, sweep_mod.spans_from_crossings,
    sweep_mod.spans, sweep_mod.fill_span, sweep_mod.fill_path_aliased, sweep_mod.transform_path

local coverage_buffer, coverage_at, set_coverage, ink, max_coverage_difference =
    coverage_mod.coverage_buffer, coverage_mod.coverage_at, coverage_mod.set_coverage, coverage_mod.ink, coverage_mod.max_coverage_difference
local rasterize_centers = shapes_mod.rasterize_centers
local filled = winding_mod.filled
local translation, scaling = matrix_mod.translation, matrix_mod.scaling
local ppm_pixel, canvas_to_p6, max_channel_difference, read_file =
    ppm_mod.ppm_pixel, ppm_mod.canvas_to_p6, ppm_mod.max_channel_difference, ppm_mod.read_file

-- ---- chapter06-edges.feature -----------------------------------------------

T.test("A rectangle has two edges in its table", function()
  local p = polygon(point(2, 2), point(6, 2), point(6, 6), point(2, 6))
  local t = edge_table(p)
  T.assert_exact(#t, 2)
  T.assert_eq(t[1].y_top, 2)
  T.assert_eq(t[1].y_bottom, 6)
  T.assert_eq(t[1].x_top, 2)
  T.assert_eq(t[1].slope, 0)
  T.assert_exact(t[1].direction, -1)
  T.assert_eq(t[2].x_top, 6)
  T.assert_exact(t[2].direction, 1)
end)

T.test("A triangle's edges carry their slopes", function()
  local p = polygon(point(0, 0), point(10, 0), point(5, 10))
  local t = edge_table(p)
  T.assert_exact(#t, 2)
  T.assert_eq(t[1].x_top, 0)
  T.assert_eq(t[1].slope, 0.5)
  T.assert_exact(t[1].direction, -1)
  T.assert_eq(t[2].x_top, 10)
  T.assert_eq(t[2].slope, -0.5)
  T.assert_exact(t[2].direction, 1)
end)

T.test("The table is sorted by top, then by x at the top", function()
  local p = path()
  move_to(p, point(2, 2))
  line_to(p, point(4, 1)); line_to(p, point(6, 3)); line_to(p, point(8, 1))
  line_to(p, point(9, 6)); line_to(p, point(1, 6))
  close(p)
  local t = edge_table(p)
  T.assert_exact(#t, 5)
  T.assert_eq(t[1].y_top, 1); T.assert_eq(t[1].x_top, 4)
  T.assert_eq(t[2].y_top, 1); T.assert_eq(t[2].x_top, 4)
  T.assert_eq(t[3].y_top, 1); T.assert_eq(t[3].x_top, 8)
  T.assert_eq(t[4].y_top, 1); T.assert_eq(t[4].x_top, 8)
  T.assert_eq(t[5].y_top, 2); T.assert_eq(t[5].x_top, 2)
end)

T.test("A horizontal edge is dropped, not clamped", function()
  local p = polygon(point(0, 0), point(10, 0), point(10, 5), point(0, 5))
  local t = edge_table(p)
  T.assert_exact(#t, 2)
  T.assert_eq(t[1].x_top, 0)
  T.assert_eq(t[2].x_top, 10)
end)

T.test("An edge knows where it crosses a height", function()
  local p = polygon(point(0, 0), point(10, 0), point(5, 10))
  local t = edge_table(p)
  T.assert_eq(x_at(t[1], 4), 2)
  T.assert_eq(x_at(t[2], 4), 8)
  T.assert_eq(x_at(t[1], 0.5), 0.25)
end)

T.test("The edge table is the same whichever way the path was drawn", function()
  local a = polygon(point(0, 0), point(10, 0), point(5, 10))
  local b = polygon(point(0, 0), point(5, 10), point(10, 0))
  local ta, tb = edge_table(a), edge_table(b)
  T.assert_eq(ta[1].x_top, tb[1].x_top)
  T.assert_eq(ta[1].slope, tb[1].slope)
  T.assert_exact(ta[1].direction, -1)
  T.assert_exact(tb[1].direction, 1)
end)

-- ---- chapter06-spans.feature -----------------------------------------------

T.test("Crossings on a row, sorted by x", function()
  local p = polygon(point(2, 2), point(6, 2), point(6, 6), point(2, 6))
  local xs = crossings_on_row(edge_table(p), 3.5)
  T.assert_crossing_list_eq(xs, { { 2, -1 }, { 6, 1 } })
  T.assert_exact(#crossings_on_row(edge_table(p), 1.5), 0)
  T.assert_exact(#crossings_on_row(edge_table(p), 6), 0)
  T.assert_exact(#crossings_on_row(edge_table(p), 2), 2)
end)

T.test("The star's crossings through its middle", function()
  local p = renders.star()
  local xs = crossings_on_row(edge_table(p), 80.5)
  T.assert_exact(#xs, 4)
  T.assert_crossing_list_eq(xs, { { 43.6988, -1 }, { 57.7556, -1 }, { 103.2444, 1 }, { 117.3012, 1 } })
end)

T.test("Spans from crossings under each rule", function()
  local xs = { { 1, 1 }, { 3, 1 }, { 5, -1 }, { 7, -1 } }
  T.assert_span_list_eq(spans_from_crossings(xs, "nonzero"), { { 1, 7 } })
  T.assert_span_list_eq(spans_from_crossings(xs, "evenodd"), { { 1, 3 }, { 5, 7 } })
  T.assert_span_list_eq(spans_from_crossings({}, "nonzero"), {})
end)

T.test("The spans of an axis-aligned rectangle are exact", function()
  local p = polygon(point(1.25, 2), point(4.75, 2), point(4.75, 5), point(1.25, 5))
  T.assert_span_list_eq(spans(p, "nonzero", 1), {})
  T.assert_span_list_eq(spans(p, "nonzero", 2), { { 1.25, 4.75 } })
  T.assert_span_list_eq(spans(p, "nonzero", 4), { { 1.25, 4.75 } })
  T.assert_span_list_eq(spans(p, "nonzero", 5), {})
end)

T.test("A rectangle whose edges sit on sample heights", function()
  local p = polygon(point(1.5, 2.5), point(4.5, 2.5), point(4.5, 5.5), point(1.5, 5.5))
  T.assert_span_list_eq(spans(p, "nonzero", 1), {})
  T.assert_span_list_eq(spans(p, "nonzero", 2), { { 1.5, 4.5 } })
  T.assert_span_list_eq(spans(p, "nonzero", 4), { { 1.5, 4.5 } })
  T.assert_span_list_eq(spans(p, "nonzero", 5), {})
end)

local triangle_span_cases = {
  { 0, 0.25, 9.75 }, { 1, 0.75, 9.25 }, { 4, 2.25, 7.75 }, { 9, 4.75, 5.25 },
}
for _, row in ipairs(triangle_span_cases) do
  T.test("A triangle's spans narrow by one per row: row " .. row[1], function()
    local p = polygon(point(0, 0), point(10, 0), point(5, 10))
    T.assert_span_list_eq(spans(p, "nonzero", row[1]), { { row[2], row[3] } })
  end)
end

T.test("The row past the triangle's apex has no span", function()
  local p = polygon(point(0, 0), point(10, 0), point(5, 10))
  T.assert_span_list_eq(spans(p, "nonzero", 10), {})
end)

T.test("A flat top is not a span of its own", function()
  local p = polygon(point(0, 0), point(10, 0), point(10, 5), point(0, 5))
  T.assert_exact(#edge_table(p), 2)
  T.assert_span_list_eq(spans(p, "nonzero", 0), { { 0, 10 } })
  T.assert_span_list_eq(spans(p, "nonzero", 4), { { 0, 10 } })
  T.assert_span_list_eq(spans(p, "nonzero", 5), {})
end)

T.test("A ring is two spans under even-odd and one under nonzero", function()
  local p = path()
  move_to(p, point(0, 0)); line_to(p, point(10, 0)); line_to(p, point(10, 10)); line_to(p, point(0, 10)); close(p)
  move_to(p, point(3, 3)); line_to(p, point(7, 3)); line_to(p, point(7, 7)); line_to(p, point(3, 7)); close(p)
  T.assert_span_list_eq(spans(p, "nonzero", 5), { { 0, 10 } })
  T.assert_span_list_eq(spans(p, "evenodd", 5), { { 0, 3 }, { 7, 10 } })
end)

T.test("The star's spans through its middle", function()
  local p = renders.star()
  T.assert_span_list_eq(spans(p, "nonzero", 80), { { 43.6988, 117.3012 } })
  T.assert_span_list_eq(spans(p, "evenodd", 80), { { 43.6988, 57.7556 }, { 103.2444, 117.3012 } })
end)

T.test("fill_span fills the pixels whose centers are in the span", function()
  local cov = coverage_buffer(8, 3)
  fill_span(cov, 1, 1.25, 4.75)
  T.assert_eq(coverage_at(cov, 0, 1), 0)
  T.assert_eq(coverage_at(cov, 1, 1), 1)
  T.assert_eq(coverage_at(cov, 4, 1), 1)
  T.assert_eq(coverage_at(cov, 5, 1), 0)
  T.assert_eq(coverage_at(cov, 2, 0), 0)
  T.assert_eq(ink(cov), 4)
end)

T.test("The span is half-open at its right end", function()
  local cov = coverage_buffer(8, 3)
  fill_span(cov, 1, 1.5, 4.5)
  T.assert_eq(coverage_at(cov, 1, 1), 1)
  T.assert_eq(coverage_at(cov, 3, 1), 1)
  T.assert_eq(coverage_at(cov, 4, 1), 0)
  T.assert_eq(ink(cov), 3)
end)

T.test("A span may run off either side of the buffer", function()
  local a, b, c = coverage_buffer(8, 3), coverage_buffer(8, 3), coverage_buffer(8, 3)
  fill_span(a, 1, -3, 2.5)
  fill_span(b, 1, 6.5, 20)
  fill_span(c, 1, 2.5, 2.5)
  T.assert_eq(ink(a), 2)
  T.assert_eq(coverage_at(a, 1, 1), 1)
  T.assert_eq(ink(b), 2)
  T.assert_eq(coverage_at(b, 6, 1), 1)
  T.assert_eq(ink(c), 0)
end)

-- ---- chapter06-sweep.feature -----------------------------------------------

T.test("Two buffers that differ", function()
  local a, b = coverage_buffer(3, 3), coverage_buffer(3, 3)
  set_coverage(a, 1, 1, 1)
  set_coverage(b, 1, 1, 0.25)
  T.assert_eq(max_coverage_difference(a, b), 0.75)
  T.assert_eq(max_coverage_difference(a, a), 0)
end)

T.test("Buffers of different sizes are as different as it gets", function()
  local a, b = coverage_buffer(3, 3), coverage_buffer(3, 4)
  T.assert_eq(max_coverage_difference(a, b), 1)
end)

T.test("A rectangle (sweep)", function()
  local p = polygon(point(2, 2), point(6, 2), point(6, 6), point(2, 6))
  local cov = fill_path_aliased(p, "nonzero", 8, 8)
  T.assert_eq(coverage_at(cov, 2, 2), 1)
  T.assert_eq(coverage_at(cov, 5, 5), 1)
  T.assert_eq(coverage_at(cov, 6, 5), 0)
  T.assert_eq(coverage_at(cov, 5, 6), 0)
  T.assert_eq(coverage_at(cov, 1, 2), 0)
  T.assert_eq(ink(cov), 16)
  T.assert_eq(max_coverage_difference(cov, rasterize_centers(filled(p, "nonzero"), 8, 8)), 0)
end)

T.test("A triangle (sweep)", function()
  local p = polygon(point(0, 0), point(10, 0), point(5, 10))
  local cov = fill_path_aliased(p, "nonzero", 20, 20)
  T.assert_eq(coverage_at(cov, 0, 0), 1)
  T.assert_eq(coverage_at(cov, 9, 0), 1)
  T.assert_eq(coverage_at(cov, 10, 0), 0)
  T.assert_eq(coverage_at(cov, 4, 8), 1)
  T.assert_eq(coverage_at(cov, 3, 8), 0)
  T.assert_eq(coverage_at(cov, 5, 9), 0)
  T.assert_eq(ink(cov), 50)
  T.assert_eq(max_coverage_difference(cov, rasterize_centers(filled(p, "nonzero"), 20, 20)), 0)
end)

T.test("The same triangle drawn the other way round (sweep)", function()
  local a = polygon(point(0, 0), point(10, 0), point(5, 10))
  local b = polygon(point(0, 0), point(5, 10), point(10, 0))
  local ca = fill_path_aliased(a, "nonzero", 20, 20)
  local cb = fill_path_aliased(b, "nonzero", 20, 20)
  T.assert_eq(max_coverage_difference(ca, cb), 0)
end)

T.test("A polygon circle", function()
  local p = circle_path(10.3, 9.7, 7, 12)
  local cov = fill_path_aliased(p, "nonzero", 20, 20)
  T.assert_eq(ink(cov), 145)
  T.assert_eq(max_coverage_difference(cov, rasterize_centers(filled(p, "nonzero"), 20, 20)), 0)
end)

T.test("The star, both rules, matches chapter 5 pixel for pixel", function()
  local p = renders.star()
  local nz = fill_path_aliased(p, "nonzero", 160, 160)
  local eo = fill_path_aliased(p, "evenodd", 160, 160)
  T.assert_eq(ink(nz), 5480)
  T.assert_eq(ink(eo), 3780)
  T.assert_eq(coverage_at(nz, 80, 80), 1)
  T.assert_eq(coverage_at(eo, 80, 80), 0)
  T.assert_eq(max_coverage_difference(nz, rasterize_centers(filled(p, "nonzero"), 160, 160)), 0)
  T.assert_eq(max_coverage_difference(eo, rasterize_centers(filled(p, "evenodd"), 160, 160)), 0)
end)

T.test("An edge that starts on a sample height is active there, and one that ends there is not", function()
  local p = polygon(point(1.5, 2.5), point(4.5, 2.5), point(4.5, 5.5), point(1.5, 5.5))
  local cov = fill_path_aliased(p, "nonzero", 8, 8)
  T.assert_eq(coverage_at(cov, 2, 1), 0)
  T.assert_eq(coverage_at(cov, 2, 2), 1)
  T.assert_eq(coverage_at(cov, 2, 4), 1)
  T.assert_eq(coverage_at(cov, 2, 5), 0)
  T.assert_eq(coverage_at(cov, 1, 3), 1)
  T.assert_eq(coverage_at(cov, 4, 3), 0)
  T.assert_eq(ink(cov), 9)
  T.assert_eq(max_coverage_difference(cov, rasterize_centers(filled(p, "nonzero"), 8, 8)), 0)
end)

T.test("A polygon larger than the buffer fills it", function()
  local p = polygon(point(-5, -5), point(30, -5), point(30, 30), point(-5, 30))
  local cov = fill_path_aliased(p, "nonzero", 8, 8)
  T.assert_eq(ink(cov), 64)
end)

T.test("An empty path fills nothing", function()
  local p = path()
  local cov = fill_path_aliased(p, "nonzero", 8, 8)
  T.assert_eq(ink(cov), 0)
end)

T.test("transform_path takes every point through the matrix and keeps the flags", function()
  local p = polygon(point(1.25, 2), point(4.75, 2), point(4.75, 5), point(1.25, 5))
  local q = transform_path(p, translation(10, 20))
  T.assert_exact(#subpaths(q), 1)
  T.assert_true(subpaths(q)[1].closed)
  T.assert_tuple_eq(subpaths(q)[1].points[1], point(11.25, 22))
  T.assert_tuple_eq(subpaths(q)[1].points[3], point(14.75, 25))
  T.assert_tuple_eq(subpaths(p)[1].points[1], point(1.25, 2))
end)

T.test("A transformed star fills where the transform put it", function()
  local p = transform_path(renders.star(), translation(10, 10) * scaling(0.11, 0.11) * translation(-80.5, -80.5))
  local nz = fill_path_aliased(p, "nonzero", 20, 20)
  local eo = fill_path_aliased(p, "evenodd", 20, 20)
  T.assert_bounds_eq(bounds(p), { 2.6769, 2.3, 17.3231, 16.2294 })
  T.assert_eq(ink(nz), 60)
  T.assert_eq(ink(eo), 40)
  T.assert_eq(max_coverage_difference(nz, rasterize_centers(filled(p, "nonzero"), 20, 20)), 0)
end)

-- ---- chapter06-plate.feature -----------------------------------------------

T.test("The unit star", function()
  local p = renders.unit_star()
  T.assert_exact(#edges(p), 5)
  T.assert_tuple_eq(subpaths(p)[1].points[1], point(0, -1))
  T.assert_tuple_eq(subpaths(p)[1].points[2], point(0.5878, 0.809))
  T.assert_tuple_eq(subpaths(p)[1].points[3], point(-0.9511, -0.309))
  T.assert_bounds_eq(bounds(p), { -0.9511, -1, 0.9511, 0.809 })
end)

T.test("The spiral", function()
  local c = renders.spiral()
  local ref = read_file("reference/chapter-06/spiral.ppm")
  local p6 = canvas_to_p6(c)
  T.assert_exact(c.width, 320)
  T.assert_exact(c.height, 320)
  local function check(x, y, rr, gg, bb)
    local r, g, b = ppm_pixel(p6, x, y)
    T.assert_eq(r, rr, 1); T.assert_eq(g, gg, 1); T.assert_eq(b, bb, 1)
  end
  check(180, 160, 243, 196, 89)
  check(183, 171, 124, 196, 237)
  check(179, 183, 237, 137, 149)
  check(104, 139, 237, 137, 149)
  check(230, 111, 124, 196, 237)
  check(32, 137, 124, 196, 237)
  check(34, 104, 237, 137, 149)
  check(160, 160, 39, 39, 44)
  check(5, 5, 39, 39, 44)
  check(300, 20, 39, 39, 44)
  T.assert_true(max_channel_difference(p6, ref) <= 1)
end)

T.test("Plate 6", function()
  local c = renders.plate_06()
  local ref = read_file("reference/chapter-06/plate-06.ppm")
  local p6 = canvas_to_p6(c)
  T.assert_exact(c.width, 640)
  T.assert_exact(c.height, 640)
  local function check(x, y, rr, gg, bb)
    local r, g, b = ppm_pixel(p6, x, y)
    T.assert_eq(r, rr, 1); T.assert_eq(g, gg, 1); T.assert_eq(b, bb, 1)
  end
  check(360, 320, 243, 196, 89)
  check(68, 208, 237, 137, 149)
  check(320, 320, 39, 39, 44)
  T.assert_true(max_channel_difference(p6, ref) <= 1)
end)
