-- features/chapter02-*.feature, translated one scenario at a time.
local T = require("helpers")
local color_mod = require("color")
local canvas_mod = require("canvas")
local ppm_mod = require("ppm")
local coverage_mod = require("coverage")
local shapes_mod = require("shapes")
local renders = require("renders")

local color = color_mod.color
local canvas, write_pixel, pixel_at = canvas_mod.canvas, canvas_mod.write_pixel, canvas_mod.pixel_at
local canvas_to_ppm, canvas_to_p6, ppm_pixel, distinct_values, max_channel_difference, read_file =
    ppm_mod.canvas_to_ppm, ppm_mod.canvas_to_p6, ppm_mod.ppm_pixel, ppm_mod.distinct_values, ppm_mod.max_channel_difference, ppm_mod.read_file

local coverage_buffer, coverage_at, set_coverage, ink, magnify, paint_through =
    coverage_mod.coverage_buffer, coverage_mod.coverage_at, coverage_mod.set_coverage, coverage_mod.ink, coverage_mod.magnify, coverage_mod.paint_through

local inside, circle, rectangle, half_plane, rasterize_centers, rasterize =
    shapes_mod.inside, shapes_mod.circle, shapes_mod.rectangle, shapes_mod.half_plane,
    shapes_mod.rasterize_centers, shapes_mod.rasterize
local center_inside = shapes_mod.center_inside
local coverage_fn = shapes_mod.coverage

-- ---- chapter02-shapes.feature -----------------------------------------------

T.test("A point inside a circle", function()
  local s = circle(8, 8, 5)
  T.assert_true(inside(s, 8, 8))
  T.assert_true(inside(s, 12, 8))
  T.assert_true(inside(s, 13, 8))
  T.assert_false(inside(s, 13.01, 8))
  T.assert_false(inside(s, 11.6, 11.6))
end)

T.test("A point inside a rectangle", function()
  local s = rectangle(1.25, 2.0, 4.75, 5.0)
  T.assert_true(inside(s, 3, 3))
  T.assert_true(inside(s, 1.25, 2.0))
  T.assert_true(inside(s, 4.75, 5.0))
  T.assert_false(inside(s, 1.2, 3))
  T.assert_false(inside(s, 3, 5.1))
end)

T.test("A point inside a half-plane", function()
  local s = half_plane(2.5, 0, 1, 0)
  T.assert_true(inside(s, 2.5, 7))
  T.assert_true(inside(s, 3, -4))
  T.assert_false(inside(s, 2.4, 0))
end)

T.test("The normal picks the side", function()
  local s = half_plane(2.5, 0, -1, 0)
  T.assert_true(inside(s, 2.4, 0))
  T.assert_false(inside(s, 3, 0))
end)

-- ---- chapter02-p6.feature -----------------------------------------------------

T.test("The header, then the bytes", function()
  local c = canvas(2, 1)
  write_pixel(c, 0, 0, color(1, 0, 0))
  write_pixel(c, 1, 0, color(0, 0.5, 0))
  local p6 = canvas_to_p6(c)
  T.assert_exact(p6:sub(1, 11), "P6\n2 1\n255\n")
  T.assert_exact(#p6, 17)
  T.assert_exact(p6:byte(12), 255)
  T.assert_exact(p6:byte(13), 0)
  T.assert_exact(p6:byte(16), 188)
end)

T.test("The same pixel comes back out of either format", function()
  local c = canvas(2, 1)
  write_pixel(c, 1, 0, color(0, 0.5, 0))
  local p3 = canvas_to_ppm(c)
  local p6 = canvas_to_p6(c)
  local r, g, b = ppm_pixel(p6, 1, 0)
  T.assert_exact(r, 0); T.assert_exact(g, 188); T.assert_exact(b, 0)
  r, g, b = ppm_pixel(p3, 1, 0)
  T.assert_exact(r, 0); T.assert_exact(g, 188); T.assert_exact(b, 0)
  T.assert_exact(max_channel_difference(p3, p6), 0)
  T.assert_exact(distinct_values(p6), 2)
end)

T.test("Rows go top to bottom", function()
  local c = canvas(1, 2)
  write_pixel(c, 0, 0, color(1, 0, 0))
  write_pixel(c, 0, 1, color(0, 0, 1))
  local p6 = canvas_to_p6(c)
  T.assert_exact(p6:byte(12), 255)
  T.assert_exact(p6:byte(17), 255)
  local r, g, b = ppm_pixel(p6, 0, 0)
  T.assert_exact(r, 255); T.assert_exact(g, 0); T.assert_exact(b, 0)
  r, g, b = ppm_pixel(p6, 0, 1)
  T.assert_exact(r, 0); T.assert_exact(g, 0); T.assert_exact(b, 255)
end)

T.test("The binary writer clamps too", function()
  local c = canvas(2, 1)
  write_pixel(c, 0, 0, color(1.5, 0, -0.5))
  local p6 = canvas_to_p6(c)
  T.assert_exact(p6:byte(12), 255)
  T.assert_exact(p6:byte(13), 0)
  T.assert_exact(p6:byte(14), 0)
  local r, g, b = ppm_pixel(p6, 0, 0)
  T.assert_exact(r, 255); T.assert_exact(g, 0); T.assert_exact(b, 0)
end)

T.test("Pixel bytes that look like whitespace are still pixel bytes", function()
  local c = canvas(2, 1)
  write_pixel(c, 0, 0, color(0.00304, 0.01444, 0.00304))
  write_pixel(c, 1, 0, color(1, 1, 1))
  local p6 = canvas_to_p6(c)
  T.assert_exact(#p6, 17)
  T.assert_exact(p6:byte(12), 10)
  T.assert_exact(p6:byte(13), 32)
  local r, g, b = ppm_pixel(p6, 0, 0)
  T.assert_exact(r, 10); T.assert_exact(g, 32); T.assert_exact(b, 10)
  r, g, b = ppm_pixel(p6, 1, 0)
  T.assert_exact(r, 255); T.assert_exact(g, 255); T.assert_exact(b, 255)
  T.assert_exact(max_channel_difference(canvas_to_ppm(c), p6), 0)
end)

T.test("Sizes still have to match", function()
  local c1, c2 = canvas(2, 1), canvas(1, 2)
  local p6a, p6b = canvas_to_p6(c1), canvas_to_p6(c2)
  T.assert_exact(max_channel_difference(p6a, p6b), 255)
end)

-- ---- chapter02-magnify.feature -------------------------------------------------

T.test("Every pixel becomes a block", function()
  local c = canvas(2, 1)
  write_pixel(c, 0, 0, color(1, 0, 0))
  write_pixel(c, 1, 0, color(0, 0.5, 0))
  local m = magnify(c, 3)
  T.assert_exact(m.width, 6)
  T.assert_exact(m.height, 3)
  T.assert_color_eq(pixel_at(m, 0, 0), color(1, 0, 0))
  T.assert_color_eq(pixel_at(m, 2, 2), color(1, 0, 0))
  T.assert_color_eq(pixel_at(m, 3, 0), color(0, 0.5, 0))
  T.assert_color_eq(pixel_at(m, 5, 2), color(0, 0.5, 0))
  T.assert_exact(T.count_pixels_of(m, color(1, 0, 0)), 9)
end)

T.test("Magnifying by one changes nothing", function()
  local c = canvas(2, 1)
  write_pixel(c, 1, 0, color(0, 0.5, 0))
  local m = magnify(c, 1)
  T.assert_exact(max_channel_difference(canvas_to_p6(c), canvas_to_p6(m)), 0)
end)

-- ---- chapter02-centers.feature -------------------------------------------------

T.test("A new coverage buffer is empty", function()
  local cov = coverage_buffer(4, 3)
  T.assert_exact(cov.width, 4)
  T.assert_exact(cov.height, 3)
  T.assert_eq(coverage_at(cov, 2, 1), 0)
  T.assert_eq(ink(cov), 0)
end)

T.test("Setting coverage", function()
  local cov = coverage_buffer(4, 3)
  set_coverage(cov, 2, 1, 0.75)
  T.assert_eq(coverage_at(cov, 2, 1), 0.75)
  T.assert_eq(coverage_at(cov, 1, 2), 0)
  T.assert_eq(ink(cov), 0.75)
end)

T.test("Setting coverage outside the buffer is ignored, and reading it gives 0", function()
  local cov = coverage_buffer(4, 3)
  set_coverage(cov, -1, 1, 1)
  set_coverage(cov, 4, 1, 1)
  set_coverage(cov, 1, 3, 1)
  T.assert_eq(ink(cov), 0)
  T.assert_eq(coverage_at(cov, -1, 1), 0)
  T.assert_eq(coverage_at(cov, 4, 1), 0)
  T.assert_eq(coverage_at(cov, 1, 3), 0)
end)

T.test("The center of pixel (x, y) is (x + 0.5, y + 0.5)", function()
  local s = half_plane(2.5, 0, 1, 0)
  local t = half_plane(2.6, 0, 1, 0)
  T.assert_exact(center_inside(s, 2, 4), 1)
  T.assert_exact(center_inside(s, 1, 4), 0)
  T.assert_exact(center_inside(t, 2, 4), 0)
end)

T.test("The center question is not \"at least half\"", function()
  local s = half_plane(2.55, 0, 1, 0)
  T.assert_exact(center_inside(s, 2, 4), 0)
  T.assert_eq(coverage_fn(s, 2, 4), 0.5)
end)

T.test("A buffer need not be square (centers)", function()
  local s = rectangle(0, 0, 2, 1)
  local cov = rasterize_centers(s, 4, 2)
  T.assert_exact(cov.width, 4)
  T.assert_exact(cov.height, 2)
  T.assert_eq(coverage_at(cov, 1, 0), 1)
  T.assert_eq(coverage_at(cov, 0, 1), 0)
  T.assert_eq(ink(cov), 2)
end)

T.test("A rectangle, by asking each center", function()
  local s = rectangle(1.25, 2.0, 4.75, 5.0)
  local cov = rasterize_centers(s, 8, 8)
  T.assert_eq(coverage_at(cov, 1, 4), 1)
  T.assert_eq(coverage_at(cov, 4, 1), 0)
  T.assert_eq(coverage_at(cov, 4, 4), 1)
  T.assert_eq(coverage_at(cov, 0, 3), 0)
  T.assert_eq(coverage_at(cov, 5, 3), 0)
  T.assert_eq(coverage_at(cov, 2, 1), 0)
  T.assert_eq(coverage_at(cov, 2, 5), 0)
  T.assert_eq(ink(cov), 12)
end)

T.test("A disc, by asking each center", function()
  local s = circle(8, 8, 5)
  local cov = rasterize_centers(s, 16, 16)
  T.assert_exact(cov.width, 16)
  T.assert_exact(cov.height, 16)
  T.assert_eq(coverage_at(cov, 8, 8), 1)
  T.assert_eq(coverage_at(cov, 3, 8), 1)
  T.assert_eq(coverage_at(cov, 12, 8), 1)
  T.assert_eq(coverage_at(cov, 2, 8), 0)
  T.assert_eq(coverage_at(cov, 13, 8), 0)
  T.assert_eq(coverage_at(cov, 4, 4), 1)
  T.assert_eq(coverage_at(cov, 3, 4), 0)
  T.assert_eq(ink(cov), 80)
end)

-- ---- chapter02-paint.feature ----------------------------------------------

T.test("Half coverage is half the paint", function()
  local c = canvas(1, 1)
  local cov = coverage_buffer(1, 1)
  set_coverage(cov, 0, 0, 0.5)
  paint_through(c, cov, color(1, 1, 1))
  T.assert_color_eq(pixel_at(c, 0, 0), color(0.5, 0.5, 0.5))
end)

T.test("Paint over something that isn't black", function()
  local c = canvas(1, 1)
  local cov = coverage_buffer(1, 1)
  canvas_mod.fill(c, color(0.2, 0.2, 0.2))
  set_coverage(cov, 0, 0, 0.25)
  paint_through(c, cov, color(1, 0, 0))
  T.assert_color_eq(pixel_at(c, 0, 0), color(0.4, 0.15, 0.15))
end)

T.test("Zero leaves it alone and one replaces it", function()
  local c = canvas(2, 1)
  local cov = coverage_buffer(2, 1)
  canvas_mod.fill(c, color(0.2, 0.2, 0.2))
  set_coverage(cov, 1, 0, 1)
  paint_through(c, cov, color(1, 0, 0))
  T.assert_color_eq(pixel_at(c, 0, 0), color(0.2, 0.2, 0.2))
  T.assert_color_eq(pixel_at(c, 1, 0), color(1, 0, 0))
end)

T.test("The arithmetic is on light, whatever the switch says (paint_through)", function()
  T.with_linear_blending(false, function()
    local c = canvas(1, 1)
    local cov = coverage_buffer(1, 1)
    set_coverage(cov, 0, 0, 0.5)
    paint_through(c, cov, color(1, 1, 1))
    local ppm = canvas_to_ppm(c)
    T.assert_color_eq(pixel_at(c, 0, 0), color(0.5, 0.5, 0.5))
    local r, g, b = ppm_pixel(ppm, 0, 0)
    T.assert_exact(r, 188); T.assert_exact(g, 188); T.assert_exact(b, 188)
  end)
end)

T.test("The disc by centers", function()
  local c = renders.disc_centers()
  local ref = read_file("reference/chapter-02/disc-centers.ppm")
  local p6 = canvas_to_p6(c)
  T.assert_exact(c.width, 320)
  T.assert_exact(c.height, 320)
  local r, g, b = ppm_pixel(p6, 160, 160)
  T.assert_eq(r, 243, 1); T.assert_eq(g, 196, 1); T.assert_eq(b, 89, 1)
  r, g, b = ppm_pixel(p6, 124, 36)
  T.assert_eq(r, 39, 1); T.assert_eq(g, 39, 1); T.assert_eq(b, 44, 1)
  r, g, b = ppm_pixel(p6, 132, 36)
  T.assert_eq(r, 243, 1); T.assert_eq(g, 196, 1); T.assert_eq(b, 89, 1)
  T.assert_exact(distinct_values(p6), 5)
  T.assert_true(max_channel_difference(p6, ref) <= 1)
end)

-- ---- chapter02-coverage.feature ---------------------------------------------

T.test("The sixty-four sample points", function()
  local s = half_plane(2.5, 0, 1, 0)
  T.assert_eq(coverage_fn(s, 2, 4), 0.5)
  T.assert_eq(coverage_fn(s, 1, 4), 0)
  T.assert_eq(coverage_fn(s, 3, 4), 1)
end)

T.test("A rectangle is covered exactly, when its edges land on sample boundaries", function()
  local s = rectangle(1.25, 2.0, 4.75, 5.0)
  local cov = rasterize(s, 8, 8)
  T.assert_eq(coverage_at(cov, 0, 2), 0)
  T.assert_eq(coverage_at(cov, 1, 2), 0.75)
  T.assert_eq(coverage_at(cov, 2, 2), 1)
  T.assert_eq(coverage_at(cov, 3, 2), 1)
  T.assert_eq(coverage_at(cov, 4, 2), 0.75)
  T.assert_eq(coverage_at(cov, 5, 2), 0)
  T.assert_eq(coverage_at(cov, 2, 1), 0)
  T.assert_eq(coverage_at(cov, 2, 5), 0)
  T.assert_eq(ink(cov), 10.5)
end)

T.test("Neither need the buffer be square here", function()
  local s = rectangle(0, 0, 2, 1)
  local cov = rasterize(s, 4, 2)
  T.assert_exact(cov.width, 4)
  T.assert_exact(cov.height, 2)
  T.assert_eq(coverage_at(cov, 1, 0), 1)
  T.assert_eq(coverage_at(cov, 2, 0), 0)
  T.assert_eq(coverage_at(cov, 0, 1), 0)
  T.assert_eq(ink(cov), 2)
end)

T.test("A half-plane through a pixel center covers half of it", function()
  local s = half_plane(2.5, 4.5, 0.6, 0.8)
  T.assert_eq(coverage_fn(s, 2, 4), 0.5)
end)

T.test("Except when the grid conspires", function()
  local s = half_plane(2.5, 4.5, 1, 1)
  T.assert_eq(coverage_fn(s, 2, 4), 0.5625)
end)

T.test("A disc is only ever approximately covered", function()
  local s = circle(8, 8, 5)
  local cov = rasterize(s, 16, 16)
  T.assert_eq(coverage_at(cov, 8, 8), 1)
  T.assert_eq(coverage_at(cov, 3, 8), 0.96875)
  T.assert_eq(coverage_at(cov, 12, 8), 0.96875)
  T.assert_eq(coverage_at(cov, 4, 4), 0.5625)
  T.assert_eq(coverage_at(cov, 3, 4), 0)
  T.assert_eq(ink(cov), 78.5)
  T.assert_eq(ink(cov), 78.5398, 0.1)
end)

T.test("The disc by coverage", function()
  local c = renders.disc_coverage()
  local ref = read_file("reference/chapter-02/disc-coverage.ppm")
  local p6 = canvas_to_p6(c)
  T.assert_exact(c.width, 320)
  T.assert_exact(c.height, 320)
  local r, g, b = ppm_pixel(p6, 160, 160)
  T.assert_eq(r, 243, 1); T.assert_eq(g, 196, 1); T.assert_eq(b, 89, 1)
  r, g, b = ppm_pixel(p6, 124, 36)
  T.assert_eq(r, 157, 1); T.assert_eq(g, 127, 1); T.assert_eq(b, 64, 1)
  T.assert_true(max_channel_difference(p6, ref) <= 1)
end)

-- ---- chapter02-twice.feature -------------------------------------------------

T.test("Half coverage, painted twice, is three quarters", function()
  local c = canvas(1, 1)
  local cov = coverage_buffer(1, 1)
  set_coverage(cov, 0, 0, 0.5)
  paint_through(c, cov, color(1, 1, 1))
  paint_through(c, cov, color(1, 1, 1))
  T.assert_color_eq(pixel_at(c, 0, 0), color(0.75, 0.75, 0.75))
end)

T.test("The disc, once and twice", function()
  local c = renders.painted_twice()
  local ref = read_file("reference/chapter-02/painted-twice.ppm")
  local p6 = canvas_to_p6(c)
  T.assert_exact(c.width, 480)
  T.assert_exact(c.height, 240)
  local r, g, b = ppm_pixel(p6, 120, 120)
  T.assert_eq(r, 243, 1); T.assert_eq(g, 196, 1); T.assert_eq(b, 89, 1)
  r, g, b = ppm_pixel(p6, 360, 120)
  T.assert_eq(r, 243, 1); T.assert_eq(g, 196, 1); T.assert_eq(b, 89, 1)
  r, g, b = ppm_pixel(p6, 93, 27)
  T.assert_eq(r, 157, 1); T.assert_eq(g, 127, 1); T.assert_eq(b, 64, 1)
  r, g, b = ppm_pixel(p6, 333, 27)
  T.assert_eq(r, 194, 1); T.assert_eq(g, 156, 1); T.assert_eq(b, 74, 1)
  T.assert_true(max_channel_difference(p6, ref) <= 1)
end)

-- ---- chapter02-plate.feature -------------------------------------------------

T.test("Plate 2", function()
  local c = renders.plate_02()
  local ref = read_file("reference/chapter-02/plate-02.ppm")
  local p6 = canvas_to_p6(c)
  T.assert_exact(c.width, 480)
  T.assert_exact(c.height, 240)
  local r, g, b = ppm_pixel(p6, 120, 120)
  T.assert_eq(r, 243, 1); T.assert_eq(g, 196, 1); T.assert_eq(b, 89, 1)
  r, g, b = ppm_pixel(p6, 360, 120)
  T.assert_eq(r, 243, 1); T.assert_eq(g, 196, 1); T.assert_eq(b, 89, 1)
  r, g, b = ppm_pixel(p6, 93, 27)
  T.assert_eq(r, 39, 1); T.assert_eq(g, 39, 1); T.assert_eq(b, 44, 1)
  r, g, b = ppm_pixel(p6, 333, 27)
  T.assert_eq(r, 157, 1); T.assert_eq(g, 127, 1); T.assert_eq(b, 64, 1)
  T.assert_true(max_channel_difference(p6, ref) <= 1)
end)
