-- features/chapter05-*.feature, translated one scenario at a time.
local T = require("helpers")
local tuple_mod = require("tuple")
local path_mod = require("path")
local winding_mod = require("winding")
local shapes_mod = require("shapes")
local coverage_mod = require("coverage")
local ppm_mod = require("ppm")
local renders = require("renders")

local point = tuple_mod.point
local path, move_to, line_to, close, subpaths, edges, bounds, polygon, circle_path =
    path_mod.path, path_mod.move_to, path_mod.line_to, path_mod.close, path_mod.subpaths,
    path_mod.edges, path_mod.bounds, path_mod.polygon, path_mod.circle_path
local crossings, winding_at, inside_nonzero, inside_evenodd, filled =
    winding_mod.crossings, winding_mod.winding_at, winding_mod.inside_nonzero, winding_mod.inside_evenodd, winding_mod.filled
local rasterize, rasterize_within, inside = shapes_mod.rasterize, shapes_mod.rasterize_within, shapes_mod.inside
local ink, coverage_at = coverage_mod.ink, coverage_mod.coverage_at
local canvas_to_p6, ppm_pixel, max_channel_difference, read_file =
    ppm_mod.canvas_to_p6, ppm_mod.ppm_pixel, ppm_mod.max_channel_difference, ppm_mod.read_file

-- ---- chapter05-paths.feature -----------------------------------------------

T.test("An empty path", function()
  local p = path()
  T.assert_exact(#subpaths(p), 0)
  T.assert_exact(#edges(p), 0)
  T.assert_bounds_eq(bounds(p), { 0, 0, 0, 0 })
end)

T.test("A triangle, closed", function()
  local p = path()
  move_to(p, point(1, 1))
  line_to(p, point(9, 1))
  line_to(p, point(5, 8))
  close(p)
  T.assert_exact(#subpaths(p), 1)
  T.assert_true(subpaths(p)[1].closed)
  T.assert_exact(#subpaths(p)[1].points, 3)
  T.assert_tuple_eq(subpaths(p)[1].points[3], point(5, 8))
  T.assert_exact(#edges(p), 3)
  T.assert_tuple_eq(edges(p)[3][1], point(5, 8))
  T.assert_tuple_eq(edges(p)[3][2], point(1, 1))
  T.assert_bounds_eq(bounds(p), { 1, 1, 9, 8 })
end)

T.test("A triangle left open still has three edges", function()
  local p = path()
  move_to(p, point(1, 1))
  line_to(p, point(9, 1))
  line_to(p, point(5, 8))
  T.assert_false(subpaths(p)[1].closed)
  T.assert_exact(#edges(p), 3)
  T.assert_tuple_eq(edges(p)[3][1], point(5, 8))
  T.assert_tuple_eq(edges(p)[3][2], point(1, 1))
end)

T.test("move_to starts a second subpath", function()
  local p = path()
  move_to(p, point(0, 0)); line_to(p, point(10, 0)); line_to(p, point(10, 10)); line_to(p, point(0, 10)); close(p)
  move_to(p, point(3, 3)); line_to(p, point(3, 7)); line_to(p, point(7, 7)); line_to(p, point(7, 3)); close(p)
  T.assert_exact(#subpaths(p), 2)
  T.assert_tuple_eq(subpaths(p)[2].points[1], point(3, 3))
  T.assert_exact(#edges(p), 8)
  T.assert_bounds_eq(bounds(p), { 0, 0, 10, 10 })
end)

T.test("line_to after a close starts a new subpath where the closed one began", function()
  local p = path()
  move_to(p, point(1, 1)); line_to(p, point(4, 1)); line_to(p, point(4, 4)); close(p)
  line_to(p, point(9, 9))
  T.assert_exact(#subpaths(p), 2)
  T.assert_false(subpaths(p)[2].closed)
  T.assert_exact(#subpaths(p)[2].points, 2)
  T.assert_tuple_eq(subpaths(p)[2].points[1], point(1, 1))
  T.assert_tuple_eq(subpaths(p)[2].points[2], point(9, 9))
end)

T.test("line_to with nothing to extend behaves as move_to", function()
  local p = path()
  line_to(p, point(2, 3))
  T.assert_exact(#subpaths(p), 1)
  T.assert_exact(#subpaths(p)[1].points, 1)
  T.assert_tuple_eq(subpaths(p)[1].points[1], point(2, 3))
end)

T.test("A subpath of one point has no edges, and closing nothing does nothing", function()
  local p = path()
  close(p)
  move_to(p, point(1, 1))
  move_to(p, point(2, 2))
  T.assert_exact(#subpaths(p), 2)
  T.assert_exact(#edges(p), 0)
  T.assert_bounds_eq(bounds(p), { 1, 1, 2, 2 })
end)

T.test("A subpath of two points has two edges and encloses nothing", function()
  local p = path()
  move_to(p, point(1, 1))
  line_to(p, point(9, 9))
  T.assert_exact(#edges(p), 2)
  T.assert_exact(winding_at(p, 3, 5), 0)
end)

T.test("polygon is a closed subpath through its points", function()
  local p = polygon(point(0, 0), point(10, 0), point(10, 10), point(0, 10))
  T.assert_exact(#subpaths(p), 1)
  T.assert_true(subpaths(p)[1].closed)
  T.assert_exact(#edges(p), 4)
end)

T.test("circle_path is a polygon standing in for a circle", function()
  local p = circle_path(10, 10, 5, 8)
  T.assert_exact(#subpaths(p)[1].points, 8)
  T.assert_tuple_eq(subpaths(p)[1].points[1], point(15, 10))
  T.assert_tuple_eq(subpaths(p)[1].points[2], point(13.5355, 13.5355))
  T.assert_tuple_eq(subpaths(p)[1].points[3], point(10, 15))
  T.assert_bounds_eq(bounds(p), { 5, 5, 15, 15 })
end)

-- ---- chapter05-winding.feature -----------------------------------------------

T.test("Crossings from inside and outside a square", function()
  local p = polygon(point(0, 0), point(10, 0), point(10, 10), point(0, 10))
  T.assert_exact(crossings(p, 5, 5), 1)
  T.assert_exact(crossings(p, 15, 5), 0)
  T.assert_exact(crossings(p, -1, 5), 2)
end)

T.test("A clockwise square winds once", function()
  local p = polygon(point(0, 0), point(10, 0), point(10, 10), point(0, 10))
  T.assert_exact(winding_at(p, 5, 5), 1)
  T.assert_exact(winding_at(p, 15, 5), 0)
  T.assert_exact(winding_at(p, -1, 5), 0)
  T.assert_exact(winding_at(p, 5, -1), 0)
  T.assert_exact(winding_at(p, 5, 11), 0)
end)

T.test("The same square the other way round winds minus once", function()
  local p = polygon(point(0, 0), point(0, 10), point(10, 10), point(10, 0))
  T.assert_exact(winding_at(p, 5, 5), -1)
  T.assert_exact(crossings(p, 5, 5), 1)
end)

T.test("A ray through a vertex counts it once", function()
  local p = polygon(point(5, 0), point(10, 5), point(5, 10), point(0, 5))
  T.assert_exact(crossings(p, 2, 5), 1)
  T.assert_exact(winding_at(p, 2, 5), 1)
  T.assert_exact(crossings(p, -1, 5), 2)
  T.assert_exact(winding_at(p, -1, 5), 0)
  T.assert_exact(winding_at(p, 12, 5), 0)
  T.assert_exact(winding_at(p, 5, 5), 1)
end)

T.test("The boundary belongs to the top and the left", function()
  local p = polygon(point(0, 0), point(10, 0), point(10, 10), point(0, 10))
  T.assert_exact(winding_at(p, 5, 0), 1)
  T.assert_exact(winding_at(p, 0, 5), 1)
  T.assert_exact(winding_at(p, 0, 0), 1)
  T.assert_exact(winding_at(p, 5, 10), 0)
  T.assert_exact(winding_at(p, 10, 5), 0)
  T.assert_exact(winding_at(p, 10, 10), 0)
end)

T.test("Two rectangles that share an edge cover it once", function()
  local p = path()
  move_to(p, point(0, 0)); line_to(p, point(5, 0)); line_to(p, point(5, 10)); line_to(p, point(0, 10)); close(p)
  move_to(p, point(5, 0)); line_to(p, point(10, 0)); line_to(p, point(10, 10)); line_to(p, point(5, 10)); close(p)
  T.assert_exact(winding_at(p, 2, 5), 1)
  T.assert_exact(winding_at(p, 5, 5), 1)
  T.assert_exact(winding_at(p, 8, 5), 1)
end)

T.test("A diamond wound twice has winding number 2", function()
  local p = path()
  move_to(p, point(5, 0)); line_to(p, point(10, 5)); line_to(p, point(5, 10)); line_to(p, point(0, 5))
  line_to(p, point(5, 0)); line_to(p, point(10, 5)); line_to(p, point(5, 10)); line_to(p, point(0, 5))
  close(p)
  T.assert_exact(#edges(p), 8)
  T.assert_exact(winding_at(p, 5, 5), 2)
  T.assert_exact(crossings(p, 5, 5), 2)
  T.assert_exact(winding_at(p, 12, 5), 0)
end)

T.test("The polygon circle", function()
  local p = circle_path(10, 10, 5, 8)
  T.assert_exact(winding_at(p, 10, 10), 1)
  T.assert_exact(winding_at(p, 14.9, 10), 1)
  T.assert_exact(winding_at(p, 15, 10), 0)
  T.assert_exact(winding_at(p, 10, 5.1), 1)
  T.assert_exact(winding_at(p, 10, 4.9), 0)
end)

T.test("The pentagram's center winds twice", function()
  local p = renders.star()
  T.assert_exact(winding_at(p, 80.5, 80.5), 2)
  T.assert_exact(crossings(p, 80.5, 80.5), 2)
  T.assert_exact(winding_at(p, 80.5, 20), 1)
  T.assert_exact(winding_at(p, 30, 60), 1)
  T.assert_exact(crossings(p, 30, 60), 3)
  T.assert_exact(winding_at(p, 80.5, 120), 0)
  T.assert_exact(crossings(p, 80.5, 120), 2)
  T.assert_exact(winding_at(p, 10, 10), 0)
end)

-- ---- chapter05-rules.feature -----------------------------------------------

T.test("A single loop is inside under both rules", function()
  local p = polygon(point(0, 0), point(10, 0), point(10, 10), point(0, 10))
  T.assert_true(inside_nonzero(p, 5, 5))
  T.assert_true(inside_evenodd(p, 5, 5))
  T.assert_false(inside_nonzero(p, 15, 5))
  T.assert_false(inside_evenodd(p, 15, 5))
end)

T.test("An inner loop the other way round is a hole under both rules", function()
  local p = path()
  move_to(p, point(0, 0)); line_to(p, point(10, 0)); line_to(p, point(10, 10)); line_to(p, point(0, 10)); close(p)
  move_to(p, point(3, 3)); line_to(p, point(3, 7)); line_to(p, point(7, 7)); line_to(p, point(7, 3)); close(p)
  T.assert_exact(winding_at(p, 5, 5), 0)
  T.assert_exact(winding_at(p, 1, 1), 1)
  T.assert_false(inside_nonzero(p, 5, 5))
  T.assert_false(inside_evenodd(p, 5, 5))
  T.assert_true(inside_nonzero(p, 1, 1))
end)

T.test("An inner loop the same way round is a hole only under even-odd", function()
  local p = path()
  move_to(p, point(0, 0)); line_to(p, point(10, 0)); line_to(p, point(10, 10)); line_to(p, point(0, 10)); close(p)
  move_to(p, point(3, 3)); line_to(p, point(7, 3)); line_to(p, point(7, 7)); line_to(p, point(3, 7)); close(p)
  T.assert_exact(winding_at(p, 5, 5), 2)
  T.assert_true(inside_nonzero(p, 5, 5))
  T.assert_false(inside_evenodd(p, 5, 5))
end)

T.test("A loop wound twice vanishes under even-odd", function()
  local p = path()
  move_to(p, point(5, 0)); line_to(p, point(10, 5)); line_to(p, point(5, 10)); line_to(p, point(0, 5))
  line_to(p, point(5, 0)); line_to(p, point(10, 5)); line_to(p, point(5, 10)); line_to(p, point(0, 5))
  close(p)
  T.assert_true(inside_nonzero(p, 5, 5))
  T.assert_false(inside_evenodd(p, 5, 5))
end)

T.test("The pentagram's center is inside under nonzero and outside under even-odd", function()
  local p = renders.star()
  T.assert_true(inside_nonzero(p, 80.5, 80.5))
  T.assert_false(inside_evenodd(p, 80.5, 80.5))
  T.assert_true(inside_nonzero(p, 80.5, 20))
  T.assert_true(inside_evenodd(p, 80.5, 20))
  T.assert_false(inside_nonzero(p, 80.5, 120))
  T.assert_false(inside_evenodd(p, 80.5, 120))
end)

T.test("A filled path is a shape", function()
  local s = filled(polygon(point(2, 2), point(6, 2), point(6, 6), point(2, 6)), "nonzero")
  local cov = rasterize(s, 8, 8)
  T.assert_true(inside(s, 3, 3))
  T.assert_false(inside(s, 7, 3))
  T.assert_eq(coverage_at(cov, 3, 3), 1)
  T.assert_eq(coverage_at(cov, 1, 3), 0)
  T.assert_eq(coverage_at(cov, 6, 3), 0)
  T.assert_eq(ink(cov), 16)
end)

T.test("A filled path takes the rule seriously", function()
  local p = renders.star()
  local a = filled(p, "nonzero")
  local b = filled(p, "evenodd")
  local ca = rasterize(a, 160, 160)
  local cb = rasterize(b, 160, 160)
  T.assert_eq(coverage_at(ca, 80, 80), 1)
  T.assert_eq(coverage_at(cb, 80, 80), 0)
  T.assert_eq(coverage_at(ca, 80, 20), 1)
  T.assert_eq(coverage_at(cb, 80, 20), 1)
  T.assert_eq(coverage_at(ca, 80, 10), 0.0625)
  T.assert_eq(coverage_at(cb, 80, 10), 0.0625)
  T.assert_eq(ink(ca), 5499.9375)
  T.assert_eq(ink(cb), 3800.375)
end)

T.test("Rasterizing within the bounds gives the same coverage", function()
  local p = renders.star()
  local s = filled(p, "evenodd")
  local full = rasterize(s, 160, 160)
  local within = rasterize_within(s, bounds(p), 160, 160)
  T.assert_eq(ink(within), ink(full))
  T.assert_eq(coverage_at(within, 80, 20), coverage_at(full, 80, 20))
  T.assert_eq(coverage_at(within, 13, 58), coverage_at(full, 13, 58))
  T.assert_eq(coverage_at(within, 10, 10), 0)
end)

T.test("The box is inclusive of the pixels it touches, and clipped to the buffer", function()
  local s = filled(polygon(point(1.5, 1.5), point(6.5, 1.5), point(6.5, 6.5), point(1.5, 6.5)), "nonzero")
  local cov = rasterize_within(s, { minx = 1.5, miny = 1.5, maxx = 6.5, maxy = 6.5 }, 8, 8)
  local big = rasterize_within(s, { minx = -5, miny = -5, maxx = 20, maxy = 20 }, 8, 8)
  T.assert_eq(coverage_at(cov, 1, 1), 0.25)
  T.assert_eq(coverage_at(cov, 6, 6), 0.25)
  T.assert_eq(coverage_at(cov, 3, 3), 1)
  T.assert_eq(ink(cov), 25)
  T.assert_eq(ink(big), 25)
end)

-- ---- chapter05-plate.feature -----------------------------------------------

T.test("The pentagram", function()
  local p = renders.star()
  T.assert_exact(#subpaths(p), 1)
  T.assert_exact(#edges(p), 5)
  T.assert_tuple_eq(subpaths(p)[1].points[1], point(80.5, 10.5))
  T.assert_tuple_eq(subpaths(p)[1].points[2], point(121.645, 137.1312))
  T.assert_tuple_eq(subpaths(p)[1].points[3], point(13.926, 58.8688))
  T.assert_tuple_eq(subpaths(p)[1].points[4], point(147.074, 58.8688))
  T.assert_tuple_eq(subpaths(p)[1].points[5], point(39.355, 137.1312))
  T.assert_bounds_eq(bounds(p), { 13.926, 10.5, 147.074, 137.1312 })
end)

T.test("The star by the center question", function()
  local c = renders.star_centers()
  local ref = read_file("reference/chapter-05/star-centers.ppm")
  local p6 = canvas_to_p6(c)
  T.assert_exact(c.width, 320)
  T.assert_exact(c.height, 160)
  local function check(x, y, rr, gg, bb)
    local r, g, b = ppm_pixel(p6, x, y)
    T.assert_eq(r, rr, 1); T.assert_eq(g, gg, 1); T.assert_eq(b, bb, 1)
  end
  check(80, 80, 243, 196, 89)
  check(240, 80, 39, 39, 44)
  check(80, 20, 243, 196, 89)
  check(240, 20, 243, 196, 89)
  check(30, 60, 243, 196, 89)
  check(190, 60, 243, 196, 89)
  check(80, 120, 39, 39, 44)
  check(80, 10, 39, 39, 44)
  check(10, 10, 39, 39, 44)
  T.assert_true(max_channel_difference(p6, ref) <= 1)
end)

T.test("The star by coverage", function()
  local c = renders.star_coverage()
  local ref = read_file("reference/chapter-05/star-coverage.ppm")
  local p6 = canvas_to_p6(c)
  T.assert_exact(c.width, 320)
  T.assert_exact(c.height, 160)
  local function check(x, y, rr, gg, bb)
    local r, g, b = ppm_pixel(p6, x, y)
    T.assert_eq(r, rr, 1); T.assert_eq(g, gg, 1); T.assert_eq(b, bb, 1)
  end
  check(80, 80, 243, 196, 89)
  check(240, 80, 39, 39, 44)
  check(80, 20, 243, 196, 89)
  check(240, 20, 243, 196, 89)
  check(80, 120, 39, 39, 44)
  check(80, 10, 77, 65, 48)
  check(240, 10, 77, 65, 48)
  check(80, 11, 199, 160, 76)
  check(14, 58, 101, 83, 52)
  check(174, 58, 101, 83, 52)
  check(10, 10, 39, 39, 44)
  T.assert_true(max_channel_difference(p6, ref) <= 1)
end)

T.test("Plate 5", function()
  local c = renders.plate_05()
  local ref = read_file("reference/chapter-05/plate-05.ppm")
  local p6 = canvas_to_p6(c)
  T.assert_exact(c.width, 640)
  T.assert_exact(c.height, 640)
  local function check(x, y, rr, gg, bb)
    local r, g, b = ppm_pixel(p6, x, y)
    T.assert_eq(r, rr, 1); T.assert_eq(g, gg, 1); T.assert_eq(b, bb, 1)
  end
  check(160, 160, 243, 196, 89)
  check(480, 160, 39, 39, 44)
  check(160, 480, 243, 196, 89)
  check(480, 480, 39, 39, 44)
  check(160, 40, 243, 196, 89)
  check(480, 360, 243, 196, 89)
  check(160, 20, 39, 39, 44)
  check(160, 341, 77, 65, 48)
  check(480, 341, 77, 65, 48)
  check(348, 437, 101, 83, 52)
  check(20, 20, 39, 39, 44)
  T.assert_true(max_channel_difference(p6, ref) <= 1)
end)
